### ISSUE TITLE
pod install error

### ISSUE THREAD

**Issue by huangboju** [devxoul/SectionReactor#2]

**Comment by devxoul** [comment]
@huangboju Which error did you get?

**Comment by huangboju** [comment]
![image](https://user-images.githubusercontent.com/14818224/33018473-8320a3f2-ce31-11e7-96ae-4fe291f2a027.png)

**Comment by devxoul** [comment]
c584cfbdb4af443ec9fc1c002b358fa8102d7197 is a patch for this. Thanks for reporting :tada:

**Comment by huangboju** [comment]
![image](https://user-images.githubusercontent.com/14818224/33018938-46619cbc-ce33-11e7-9484-a8386ba59b66.png)
![image](https://user-images.githubusercontent.com/14818224/33018957-5b1fda42-ce33-11e7-8975-9e5ec1cfafe4.png)

**Comment by devxoul** [comment]
Can you pull again?

**Comment by huangboju** [comment]
![image](https://user-images.githubusercontent.com/14818224/33019018-afd1aef8-ce33-11e7-8f57-6ea8c8f82390.png)

**Comment by huangboju** [comment]
![image](https://user-images.githubusercontent.com/14818224/33019038-bf233340-ce33-11e7-9869-1776ea02daf6.png)

**Comment by devxoul** [comment]
```console
$ git reset HEAD^ --hard
$ git pull
```

**Comment by huangboju** [comment]
It's working

**Comment by huangboju** [comment]
Sorry, i reopen this
I pulled a new package from the master branch, 
`pod install`
I got this
![image](https://user-images.githubusercontent.com/14818224/33050186-7ed3bd12-ce9e-11e7-85fb-d454d03df0d4.png)
I think it should be those swift4 branch does not exist
I modify the podfile to this
![image](https://user-images.githubusercontent.com/14818224/33050235-bb1d8c44-ce9e-11e7-9506-76557d53d2f4.png)
`pod install` and `run`
I got this
![image](https://user-images.githubusercontent.com/14818224/33050257-deda8dc6-ce9e-11e7-8821-b1bcf632e87d.png)

**Comment by devxoul** [comment]
Oh, I just fixed it. Thanks for reporting.

**Comment by huangboju** [comment]
I downloaded a new zip, but he still can not run
![image](https://user-images.githubusercontent.com/14818224/33056041-360976d8-cebe-11e7-9247-1c4387fdc13e.png)

**Comment by devxoul** [comment]
@huangboju, sorry for delay. Can you do this again? I just updated the example.

```console
$ git reset HEAD^ --hard
$ git pull
```

**Comment by huangboju** [comment]
It is working，thx
